trigger:
- master

jobs:
- job: macOS
  pool:
    vmImage: $[ coalesce(variables['VM_IMAGE'], 'macOS 10.13') ]
  strategy:
    maxParallel: 10
    matrix:
      Xcode 9.0.1:
        DEVELOPER_DIR: '/Applications/Xcode_9.0.1.app'
      Xcode 9.1:
        DEVELOPER_DIR: '/Applications/Xcode_9.1.app'
      Xcode 9.2:
        DEVELOPER_DIR: '/Applications/Xcode_9.2.app'
      Xcode 9.3.1:
        DEVELOPER_DIR: '/Applications/Xcode_9.3.1.app'
      Xcode 9.4.1:
        DEVELOPER_DIR: '/Applications/Xcode_9.4.1.app'
      Xcode 10:
        DEVELOPER_DIR: '/Applications/Xcode_10.app'
        XCODE_FLAGS_FOR_TEST: -parallel-testing-enabled NO
      Xcode 10.1:
        DEVELOPER_DIR: '/Applications/Xcode_10.1.app'
        XCODE_FLAGS_FOR_TEST: -parallel-testing-enabled NO
      Xcode 10.2:
        DEVELOPER_DIR: '/Applications/Xcode_10.2.app'
        VM_IMAGE: 'macOS 10.14'
        XCODE_FLAGS_FOR_TEST: -parallel-testing-enabled NO
      Xcode 10.2.1:
        DEVELOPER_DIR: '/Applications/Xcode_10.2.1.app'
        VM_IMAGE: 'macOS 10.14'
        XCODE_FLAGS_FOR_TEST: -parallel-testing-enabled NO
  steps:
    - script: |
        xcodebuild -version
        echo "##vso[task.setvariable variable=XCODE_FLAGS]-scheme ObjectEncoder-Package $XCODE_FLAGS_FOR_TEST"
      displayName: xcodebuild -version & set XCODE_FLAGS
    - script: >
        set -o pipefail &&
        xcodebuild $XCODE_FLAGS test |
        xcpretty -r junit -o build/reports/xcodebuild-macOS.xml
      displayName: tests on macOS
      condition: succeededOrFailed()
    - script: >
        set -o pipefail &&
        xcodebuild $XCODE_FLAGS test -sdk iphonesimulator -destination "name=iPhone 8" |
        xcpretty -r junit -o build/reports/xcodebuild-iOS.xml
      displayName: tests on iOS
      condition: succeededOrFailed()
    - script: >
        set -o pipefail &&
        xcodebuild $XCODE_FLAGS test -sdk iphonesimulator -destination "name=iPhone 5" |
        xcpretty -r junit -o build/reports/xcodebuild-iOS-32bit.xml
      displayName: tests on iOS (32-bit)
      condition: succeededOrFailed()
    - script: >
        set -o pipefail &&
        xcodebuild $XCODE_FLAGS test -sdk appletvsimulator -destination "name=Apple TV 4K" |
        xcpretty -r junit -o build/reports/xcodebuild-tvOS.xml
      displayName: tests on tvOS
      condition: succeededOrFailed()
    - script: >
        set -o pipefail &&
        xcodebuild $XCODE_FLAGS build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm" |
        xcpretty
      displayName: build on watchOS
      condition: succeededOrFailed()
    - script: >
        set -o pipefail &&
        swift test 2>&1 |
        xcpretty -r junit -o build/reports/swift-test.xml
      displayName: swift test
      condition: succeededOrFailed()
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
      condition: succeededOrFailed()
    - script: set -o pipefail && bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
      displayName: Upload coverage to codecov.io

- job: pod_lib_lint
  pool:
    vmImage: 'macOS 10.14'
  variables:
    DEVELOPER_DIR: '/Applications/Xcode_10.2.1.app'
  steps:
    - script: pod lib lint
      displayName: pod lib lint
