version: 2
jobs:

  xcode_9:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: xcodebuild -scheme ObjectEncoder-Package build-for-testing test-without-building
      - run: xcodebuild -scheme ObjectEncoder-Package build-for-testing test-without-building -sdk iphonesimulator -destination "name=iPhone 8"
      - run: xcodebuild -scheme ObjectEncoder-Package build-for-testing test-without-building -sdk appletvsimulator -destination "name=Apple TV 4K"
      - run: xcodebuild -scheme ObjectEncoder-Package build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm"
      - run: swift test

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps:
      - checkout
      - run: swift test

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9
      - linux_swift_4
