version: 2
jobs:

  xcode_9.0:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          command: |
            ( xcodebuild -scheme ObjectEncoder-Package test
              xcodebuild -scheme ObjectEncoder-Package test -sdk iphonesimulator -destination "name=iPhone 8"
              xcodebuild -scheme ObjectEncoder-Package test -sdk appletvsimulator -destination "name=Apple TV 4K"
              xcodebuild -scheme ObjectEncoder-Package build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm"
            ) | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: swift test

  xcode_9.1:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run:
          command: |
            ( xcodebuild -scheme ObjectEncoder-Package test
              xcodebuild -scheme ObjectEncoder-Package test -sdk iphonesimulator -destination "name=iPhone 8"
              xcodebuild -scheme ObjectEncoder-Package test -sdk appletvsimulator -destination "name=Apple TV 4K"
              xcodebuild -scheme ObjectEncoder-Package build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm"
            ) | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: swift test

  linux_swift_4:
    docker:
      - image: norionomura/swiftlint:swift-4.0
    steps:
      - checkout
      - run: swift test
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9.0
      - xcode_9.1
      - linux_swift_4
