version: 2
jobs:

  xcode_9:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: xcodebuild -scheme ObjectEncoder-Package test | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: xcodebuild -scheme ObjectEncoder-Package test -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: xcodebuild -scheme ObjectEncoder-Package test -sdk appletvsimulator -destination "name=Apple TV 4K" | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: xcodebuild -scheme ObjectEncoder-Package build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm" | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: swift test

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps:
      - checkout
      - run: swift test
  docker_swiftlint:
    docker:
      - image: norionomura/swiftlint:0.23.1
    steps:
      - checkout
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9
      - linux_swift_4
      - docker_swiftlint
