version: 2.1

commands:
  swiftlint:
    steps:
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

jobs:
  build_with_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: swift test

workflows:
  workflow:
    jobs:
      - build_with_image:
          name: swift-4.0.2-RELEASE
          image: norionomura/swiftlint:swift-4.0.2
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.0.3-RELEASE
          image: norionomura/swiftlint:swift-4.0.3
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.1-RELEASE
          image: norionomura/swiftlint:swift-4.1.0
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.1.1-RELEASE
          image: norionomura/swiftlint:swift-4.1.1
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.1.2-RELEASE
          image: norionomura/swiftlint:swift-4.1.2
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.1.3-RELEASE
          image: norionomura/swiftlint:swift-4.1.3
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2-RELEASE
          image: norionomura/swiftlint:swift-4.2.0
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2.1-RELEASE
          image: norionomura/swiftlint:swift-4.2.1
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2.2-RELEASE
          image: norionomura/swiftlint:swift-4.2.2
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2.3-RELEASE
          image: norionomura/swiftlint:swift-4.2.3
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2.4-RELEASE
          image: norionomura/swiftlint:swift-4.2.4
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-5.0-RELEASE
          image: norionomura/swiftlint:swift-5.0.0
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-5.0.1-RELEASE
          image: norionomura/swiftlint:swift-5.0.1
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-5.1-branch
          image: norionomura/swift:swift-5.1-branch
      - build_with_image:
          name: swift-nightly
          image: norionomura/swift:nightly
      - build_with_image:
          name: swift-tensorflow
          image: norionomura/swift-tensorflow

  daily:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_with_image:
          name: swift-5.1-branch
          image: norionomura/swift:swift-5.1-branch
