name: pod lib lint

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Sources/**'
  pull_request:
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Sources/**'

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macOS-10.14
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app
    steps:
      - uses: actions/checkout@v1
      - run: pod lib lint
