name: SwiftPM

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/swiftpm.yml'
      - 'Package*'
      - 'Sources/*/*'
      - 'Tests/*'
      - 'Tests/*/*'
  pull_request:
    paths: 
      - '.github/workflows/swiftpm.yml'
      - 'Package*'
      - 'Sources/*/*'
      - 'Tests/*'
      - 'Tests/*/*'

jobs:
  Xcode:
    strategy:
      matrix:
        xcode: ['9.4.1', '10', '10.1', '10.2.1', '10.3', '11']
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - env: { 'DEVELOPER_DIR': '/Applications/Xcode_${{ matrix.xcode }}.app' }
        run: swift -version
      - env: { 'DEVELOPER_DIR': '/Applications/Xcode_${{ matrix.xcode }}.app' }
        run: swift test --parallel

  Linux:
    strategy:
      matrix:
        tag: ['4.1', '4.2', '5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test --parallel
